name: github pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        version: 12

    - name: Install Modules
      run: npm install

    - name: Build Site
      run: npm build

    - name: Deploy
      uses: nchaulet/github-action-gh-pages@master
      with:
        args:
          GITHUB_TOKEN:${{ GITHUB_TOKEN }}
